doctrine:
    dbal:
        dbname: '%env(DATABASE_NAME)%'
        host: '%env(DATABASE_HOST)%'
        port: '%env(DATABASE_PORT)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        driver: '%env(DATABASE_DRIVER)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '8.0'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                extract: DoctrineExtensions\Query\Mysql\Extract
                dayofyear: DoctrineExtensions\Query\Mysql\DayOfYear
                week: DoctrineExtensions\Query\Mysql\Week
                month: DoctrineExtensions\Query\Mysql\Month
